version: "3.2"

services:
  backend-webservice:
    container_name: autopilot-drone-backend-webservice
    build:
      context: ./backend/webservice
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/build

  backend-rtmp-server:
    container_name: autopilot-drone-backend-rtmp-server
    build:
      context: ./backend/rtmp-server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1935:1935"
    volumes:
      - .:/build
    restart: unless-stopped

  frontend-home:
    container_name: autopilot-drone-frontend-home
    build:
      context: ./frontend/home
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend-webservice

  frontend-dashboard:
    container_name: autopilot-drone-frontend-dashboard
    build:
      context: ./frontend/dashboard
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - backend-webservice
