version: "3.2"

services:
  backend-webservice:
    container_name: autopilot-drone-backend-webservice
    build:
      context: ./backend/webservice
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - .:/build

  frontend-dashboard:
    container_name: autopilot-drone-frontend-dashboard
    build:
      context: ./frontend/dashboard
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - webservice
