version: "3.2"

services:
  backend-webservice:
    container_name: autopilot-drone-backend-webservice
    build:
      context: ./backend/webservice
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    ports:
      - "5000:5000"
    volumes:
      - .:/build

  backend-rtmp-server:
    container_name: autopilot-drone-backend-rtmp-server
    build:
      context: ./backend/rtmp-server
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    ports:
      - "1935:1935"
    volumes:
      - .:/build

  frontend-dashboard:
    container_name: autopilot-drone-frontend-dashboard
    build:
      context: ./frontend/dashboard
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      - backend-webservice
