version: "3.2"

services:
  webservice:
    container_name: autopilot-drone-webservice
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    ports:
      - "5000:5000"
    volumes:
      - .:/build

  frontend:
    container_name: autopilot-drone-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      - webservice
