apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: autopilot-drone
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 30079
  selector:
    app: redis