apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: autopilot-drone
  labels:
    app: redis
type: Opaque
data:
  redis-password: cGFzc3dvcmQ=      # base64 encoded password (e.g., "password")
