apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: autopilot-drone
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0 # Use the appropriate Redis version
        ports:
        - containerPort: 6379
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        - name: REDIS_USERNAME
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-username
        command:
        - "redis-server"
        - "--requirepass"
        - "$(REDIS_PASSWORD)"
        - "--user"
        - "$(REDIS_USERNAME)"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc # Create a PersistentVolumeClaim for data storage
