apiVersion: v1
kind: Service
metadata:
  name: autopilot-drone-backend-rtmp-server
  namespace: autopilot-drone
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 1935
    targetPort: 1935
    nodePort: 31935
    name: rtmp
  - port: 80
    targetPort: 80
    name: live
  selector:
    app: autopilot-drone-backend-rtmp-server