apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: autopilot-drone
type: Opaque
data:
  mongo-root-username: YWRtaW4=  # Base64-encoded string for "admin"
  mongo-root-password: cGFzc3dvcmQ=  # Base64-encoded string for "password"
