apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: autopilot-drone
spec:
  type: NodePort
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30017
  selector:
    app: mongodb