apiVersion: v1
kind: Service
metadata:
  name: autopilot-drone-backend-stun-server
  namespace: autopilot-drone
  labels:
    app: coturn
spec:
  type: NodePort
  selector:
    app: coturn
  ports:
    - name: stun-udp
      protocol: UDP
      port: 3478
      targetPort: 3478
      nodePort: 30478  # Custom NodePort for STUN UDP (Range: 30000-32767)
    - name: stun-tcp
      protocol: TCP
      port: 3478
      targetPort: 3478
      nodePort: 30479  # Custom NodePort for STUN TCP
    - name: turn-udp
      protocol: UDP
      port: 5349
      targetPort: 5349
      nodePort: 30549  # Custom NodePort for TURN UDP
    - name: turn-tcp
      protocol: TCP
      port: 5349
      targetPort: 5349
      nodePort: 30550  # Custom NodePort for TURN TCP
